export const SET_CURRENT_MENU = 'SET_CURRENT_MENU'

export const SET_P_TYPE_SELECT_VISIBLE = 'SET_P_TYPE_SELECT_VISIBLE'
export const SET_ADD_PROJECT_VISIBLE = 'SET_ADD_PROJECT_VISIBLE'
export const SET_ADD_CATEGORY_VISIBLE = 'SET_ADD_CATEGORY_VISIBLE'
export const SET_ADD_TASK_VISIBLE = 'SET_ADD_TASK_VISIBLE'
