export const SET_CURRENT_MENU = 'SET_CURRENT_MENU'
export const OPEN_MENU = 'OPEN_MENU'

export const SET_P_TYPE_SELECT_VISIBLE = 'SET_P_TYPE_SELECT_VISIBLE'
export const SET_ADD_PROJECT_VISIBLE = 'SET_ADD_PROJECT_VISIBLE'
export const SET_ADD_CATEGORY_VISIBLE = 'SET_ADD_CATEGORY_VISIBLE'
export const SET_ADD_TASK_VISIBLE = 'SET_ADD_TASK_VISIBLE'

export const SET_ADD_STAFF_VISIBLE = 'SET_ADD_STAFF_VISIBLE'

export const SET_DEPARTMENT_VISIBLE = 'SET_DEPARTMENT_VISIBLE'

export const SET_DAILY_VISIBLE = 'SET_DAILY_VISIBLE'

export const SET_FOLDER_VISIBLE = 'SET_FOLDER_VISIBLE'
export const SET_FILE_VISIBLE = 'SET_FILE_VISIBLE'
