export const ADD_DAILY = 'ADD_DAILY'
export const EDIT_DAILY = 'EDIT_DAILY'
export const DELETE_DAILY = 'DELETE_DAILY'
export const VIEW_DAILY = 'VIEW_DAILY'
export const POST_DAILY_FILE = 'POST_DAILY_FILE'
