export const GET_PROJECT_LIST = 'GET_PROJECT_LIST'

export const ADD_PROJECT = "ADD_PROJECT"
export const EDIT_PROJECT = "EDIT_PROJECT"
export const REMOVE_PROJECT = "REMOVE_PROJECT"

export const ADD_CATEGORY = "ADD_CATEGORY"
export const EDIT_CATEGORY = "EDIT_CATEGORY"
export const REMOVE_CATEGORY = "REMOVE_CATEGORY"

export const ADD_TASK = "ADD_TASK"
export const EDIT_TASK = "EDIT_TASK"
export const REMOVE_TASK = "REMOVE_TASK"
